runtime: python39

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

databases:
  - name: cbff-demo
    user: user

services:
  - type: web
    name: cbff-demo
    env: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn cbff-demo.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4databases:
  - name: cbff-demo
    user: user

services:
  - type: web
    name: cbff-demo
    env: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn cbff-demo.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4