version: '3'
services:
  cbffdemo-app:
    restart: always
    env_file: .env
    build: 
      context: .
    ports:
      - "5005:5005"
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - db_network
      - web_network
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:5005"
    environment:
      - DB_HOST=db
      - DB_NAME=cbffdemo-app
      - DB_USER=postgres
      - DB_PASS=password
    depends_on: 
      - cbffdemo-app

  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=cbffdemo-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - cbffdemo-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 