# Generated by Django 2.2.10 on 2021-08-08 03:40

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.PositiveIntegerField()),
                ('StockCode', models.CharField(max_length=12)),
                ('Description', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('InvoiceDate', app.utils.FormattedDateTimeField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('CustomerID', models.PositiveIntegerField()),
                ('Country', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('InvoiceNo',),
            },
        ),
    ]
