# Generated by Django 2.2.10 on 2021-08-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='InvoiceDate',
            field=models.DateTimeField(),
        ),
    ]
