# Generated by Django 2.2.10 on 2021-08-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210808_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='InvoiceDate',
        ),
    ]
