# Generated by Django 2.2.10 on 2021-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_orders_invoicedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='InvoiceDate',
            field=models.DateTimeField(auto_now=True, verbose_name='InvoiceDate'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='CustomerID',
            field=models.PositiveIntegerField(verbose_name='CustomerID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='InvoiceNo',
            field=models.PositiveIntegerField(verbose_name='InvoiceNo'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='StockCode',
            field=models.CharField(max_length=12, verbose_name='StockCode'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='UnitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='UnitPrice'),
        ),
    ]
