# Generated by Django 2.2.10 on 2021-08-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210808_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.PositiveIntegerField(verbose_name='InvoiceNo')),
                ('StockCode', models.CharField(max_length=12, verbose_name='StockCode')),
                ('Description', models.CharField(max_length=100, verbose_name='Description')),
                ('Quantity', models.IntegerField(verbose_name='Quantity')),
                ('InvoiceDate', models.DateTimeField(auto_now=True, verbose_name='InvoiceDate')),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='UnitPrice')),
                ('CustomerID', models.PositiveIntegerField(verbose_name='CustomerID')),
                ('Country', models.CharField(max_length=100, verbose_name='Country')),
            ],
            options={
                'ordering': ('InvoiceNo',),
            },
        ),
    ]
